name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install

      # must run first to build schemas.
      - name: Build
        run: npm run build:all

      - name: Lint
        run: npm run lint

      - name: Test Schemas
        run: npm run test:schemas

      - name: Test Credentials
        run: npm run test:credentials
